using System.Security.Claims;
using System.Text;
using ErrandRuns.Application;
using ErrandRuns.Domain.Common;
using ErrandRuns.Infrastructure;
using ErrandRuns.Infrastructure.Configuration;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.RateLimiting;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Serilog;
var builder=WebApplication.CreateBuilder(args);
builder.Host.UseSerilog((ctx,c)=>c.ReadFrom.Configuration(ctx.Configuration).Enrich.FromLogContext().WriteTo.Console());
var connection=builder.Configuration.GetConnectionString("SqlServer")??throw new InvalidOperationException("ConnectionStrings:SqlServer is required.");
builder.Services.AddDbContext<ErrandRunsDbContext>(o=>o.UseSqlServer(connection));
builder.Services.AddExternalServiceConfiguration(builder.Configuration);
builder.Services.AddScoped<IErrandRepository,ErrandRepository>();builder.Services.AddScoped<IRunnerRepository,RunnerRepository>();builder.Services.AddScoped<ErrandService>();builder.Services.AddScoped<IRunnerMatchingService,RunnerMatchingService>();builder.Services.AddSingleton<IPricingService,PricingService>();builder.Services.AddSingleton<IClock,SystemClock>();builder.Services.AddHttpContextAccessor();builder.Services.AddScoped<ICurrentUser,HttpCurrentUser>();
var jwt=builder.Configuration.GetSection("Jwt");var key=jwt["SigningKey"]??throw new InvalidOperationException("Jwt:SigningKey is required.");if(Encoding.UTF8.GetByteCount(key)<32)throw new InvalidOperationException("JWT key must contain at least 32 bytes.");
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(o=>o.TokenValidationParameters=new(){ValidateIssuer=true,ValidIssuer=jwt["Issuer"],ValidateAudience=true,ValidAudience=jwt["Audience"],ValidateIssuerSigningKey=true,IssuerSigningKey=new SymmetricSecurityKey(Encoding.UTF8.GetBytes(key)),ValidateLifetime=true,ClockSkew=TimeSpan.FromSeconds(30)});
builder.Services.AddAuthorization();builder.Services.AddProblemDetails();builder.Services.AddOpenApi();builder.Services.AddHealthChecks().AddDbContextCheck<ErrandRunsDbContext>();
builder.Services.AddRateLimiter(o=>o.AddFixedWindowLimiter("sensitive",x=>{x.PermitLimit=10;x.Window=TimeSpan.FromMinutes(1);x.QueueLimit=0;}));
var origins=builder.Configuration.GetSection("Cors:AllowedOrigins").Get<string[]>()??[];builder.Services.AddCors(o=>o.AddDefaultPolicy(p=>p.WithOrigins(origins).AllowAnyHeader().AllowAnyMethod()));
var app=builder.Build();app.UseExceptionHandler(e=>e.Run(async context=>{var error=context.Features.Get<IExceptionHandlerFeature>()?.Error;var status=error switch{DomainException=>409,KeyNotFoundException=>404,UnauthorizedAccessException=>403,_=>500};context.Response.StatusCode=status;await Results.Problem(statusCode:status,title:status==500?"Unexpected server error":"Request could not be completed",detail:status==500?null:error?.Message,extensions:new Dictionary<string,object?>{{"traceId",context.TraceIdentifier}}).ExecuteAsync(context);}));
app.Use(async(ctx,next)=>{ctx.Response.Headers["X-Content-Type-Options"]="nosniff";ctx.Response.Headers["Referrer-Policy"]="no-referrer";ctx.Response.Headers["X-Frame-Options"]="DENY";await next();});app.UseHttpsRedirection();app.UseCors();app.UseRateLimiter();app.UseAuthentication();app.UseAuthorization();
if(app.Environment.IsDevelopment())app.MapOpenApi();app.MapHealthChecks("/health/live",new(){Predicate=_=>false});app.MapHealthChecks("/health/ready");
var errands=app.MapGroup("/api/v1/errands").RequireAuthorization();
errands.MapPost("/",async(CreateErrand c,ErrandService s,CancellationToken ct)=>Results.Created("",await s.Create(c,ct))).RequireAuthorization(p=>p.RequireRole("Customer"));
errands.MapPost("/{id:guid}/match",async(Guid id,ErrandService s,CancellationToken ct)=>Results.Ok(await s.Match(id,ct))).RequireAuthorization(p=>p.RequireRole("Customer"));
errands.MapPost("/{id:guid}/accept",async(Guid id,ErrandService s,CancellationToken ct)=>Results.Ok(await s.Accept(id,ct))).RequireAuthorization(p=>p.RequireRole("Runner"));
errands.MapPost("/{id:guid}/stops/{stopId:guid}/start",async(Guid id,Guid stopId,ErrandService s,CancellationToken ct)=>Results.Ok(await s.StartStop(id,stopId,ct))).RequireAuthorization(p=>p.RequireRole("Runner"));
errands.MapPost("/{id:guid}/stops/{stopId:guid}/complete",async(Guid id,Guid stopId,ErrandService s,CancellationToken ct)=>Results.Ok(await s.CompleteStop(id,stopId,ct))).RequireAuthorization(p=>p.RequireRole("Runner"));
app.Run();
public sealed class HttpCurrentUser(IHttpContextAccessor accessor):ICurrentUser { public Guid UserId=>Guid.TryParse(accessor.HttpContext?.User.FindFirstValue(ClaimTypes.NameIdentifier),out var id)?id:throw new UnauthorizedAccessException();public bool IsInRole(string role)=>accessor.HttpContext?.User.IsInRole(role)==true; }
public partial class Program;
